version: "3.9"


services:
  bot:
    build:
      context: ./todo_bot
      dockerfile: Dockerfile
    command: python3 -m bot
    env_file:
      - ./todo_bot/.env
    environment:
      - BOT_TOKEN=
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_started
      todos:
        condition: service_started
      comments:
        condition: service_started

  todos:
    build:
      context: ./todo_app
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./todo_app/.env
    environment:
      - DJANGO_SUPERUSER_TG_ID=1744297788
      - DJANGO_SUPERUSER_FIRST_NAME=name
      - DJANGO_SUPERUSER_USERNAME=user
      - DJANGO_SUPERUSER_PASSWORD=1234
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_started

  comments:
    build:
      context: ./comments_service
      dockerfile: Dockerfile
    env_file:
      - ./comments_service/.env
    command: python3 -m uvicorn main:main --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_started
      todos:
        condition: service_started

  postgresql:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - "redis_data:/data"

volumes:
  pgdata:
  redis_data:
